name: Create Jira Issue

on:
  issues:
    types: [opened, closed, deleted, reopened]
  pull_request_target:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]

jobs:
  call-workflow:
    uses: ./.github/workflows/create-jira-issue.yml
    with:
      github-team: Terraform-Enterprise
      project: TFE
    secrets: inherit