name: Create Jira Issue

on:
  issues:
    types: [opened, closed, deleted, reopened]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  create-jira-issue:
    uses: hashicorp/tf-enterprise-workflows/.github/workflows/create-jira-issue.yml@main
    secrets: inherit